# Generated by Django 4.0.5 on 2023-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customeruser_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
