# Generated by Django 4.0.5 on 2023-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customeruser_email_customeruser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
