# Generated by Django 4.0.5 on 2023-05-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_featuredad_giftcategory_vendoruser_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='role',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='vendoruser',
            name='role',
            field=models.IntegerField(default='1'),
        ),
    ]
